apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    name: alpine
spec:
  containers:
  - name: nginx
    image: quay.io/collectai/alpine-curl
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
